### ISSUE TITLE
Cross Platform Consistency

### ISSUE THREAD

**Issue by ccoffrin** [jump-dev/SCS.jl#114]
This may be of interest to the SCS developers and/or the binary builder configuration.

This update to ThreePhasePowerModels highlights a few SDP models where SCS produces notably different solutions on the Linux build vs the OS X build.

https://github.com/lanl-ansi/ThreePhasePowerModels.jl/commit/ec535c4a4218a5336464e581d565c22108bc3f84

**Comment by kalmarek** [comment]
1) what blas is `libscs*` linked against?
2) did You inspect the scs log?

**Comment by ccoffrin** [comment]
Re 1, I think @juan-pablo-vielma would know...

Re 2, I did not in any detail.  Would you like me to post two log examples here?

**Comment by kalmarek** [comment]
a gist would be perfect

**Comment by ccoffrin** [comment]
Re 2, https://gist.github.com/ccoffrin/a350fd9f11760c8a1ff476068af8dbef

**Comment by kalmarek** [comment]
I think SCS does what it should do, it's just the optimal value is rather large;
If You look at the stopping criteria:
```
primal res: |Ax + s - b|_2 / (1 + |b|_2) = 7.4353e-06
dual res:   |A'y + c|_2 / (1 + |c|_2) = 8.3577e-06
rel gap: |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.5491e-06
```
these are all relative, and the two solutions are (relatively, i.e. `1e-5` of the `cx*`) close.

**Comment by ccoffrin** [comment]
Sounds reasonable, but what would be the root cause of the discrepancy across OSes?

To my surprise, my experience has been that LP and NLP solver are quite numerically consistent across different OSes, usually the differences are only noticeable beyond the numerical precision of the algorithm.

**Comment by kalmarek** [comment]
different blas?, other libraries, randomness pools (probably doesn't apply here)?

what do You see when calling with `acceleration_loopback=1, alpha=1.9`?

**Comment by ccoffrin** [comment]
The gist is updated to include the results from the modified solver parameters.  The results on the two platforms appear to be more similar in this case.

**Comment by kalmarek** [comment]
the Anderson Acceleration in SCS is numerically unstable at the moment, so You get bits of randomness in the process.

If You wish the behaviour to be consistent between the platforms, I suggest adding setting the above parameters to the solver (if user doesn't specify them, of course)

**Comment by mlubin** [comment]
> the Anderson Acceleration in SCS is numerically unstable at the moment, so you get bits of randomness in the process.

Why is a numerically unstable method used as the default? That makes things pretty challenging from a software engineering perspective.

**Comment by kalmarek** [comment]
I should have said "there are certain cases where numerical instability pronounces itself";

it will be less pronounced in 2.1.0, I believe

**Comment by odow** [comment]
Is this still an issue with the new SCS version and provided binaries?

**Comment by ccoffrin** [comment]
we have not seen this issue crop up recently as far as I know.  That said, back in 2018 we did put in significant effort into relaxing our tests to account for a lack of consistency is SDP solution values.

**Comment by odow** [comment]
Closing as we now have different binaries. Please re-open if this crops up again.
