### ISSUE TITLE
v0.7

### ISSUE THREAD

**Issue by kalmarek** [jump-dev/SCS.jl#183]
The next release will be with breaking, and since when #182 is merged we should release rather sooner than later;

Are we ok with the release, or should I write on e.g. discourse asking for additional testing (gpu support and more) before?
@mlubin  @blegat

**Comment by blegat** [comment]
IMO bumping the minor version (so v0.7 instead of v0.6.7) should be sufficient.

**Comment by odow** [comment]
Is there anything blocking a tag of 0.7? It is needed for the MOI benchmarks.

**Comment by kalmarek** [comment]
@odow I'd like to merge the GPU stuff, but I can't setup the CI, only one of the owners of the repository (here: someone from the jump-dev group) can. would you do it?

**Comment by odow** [comment]
What about tagging as-is as 0.7, then sorting out the GPU stuff and tagging as 0.8? There are a lot of commits sitting on `master` that are useful.

**Comment by kalmarek** [comment]
sure, go ahead!

**Comment by odow** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/21202#issuecomment-690685007
