### ISSUE TITLE
Fast copy

### ISSUE THREAD

**Issue by blegat** [jump-dev/SCS.jl#186]
We should speed up copy to SCS. In the model of https://github.com/jump-dev/SCS.jl/issues/181, it the copy from the `MOIU.Model` to SCS takes 30 seconds (not counting `sparse` and the creation of the `ManagedSCSMatrix` that is called in `MOI.optimize!`).
This simpler implementation directly generates the three vectors needed for `ManagedSCSMatrix` (so that `MOI.optimize!` (see https://github.com/jump-dev/SCS.jl/pull/185) is O(1)).
```julia
function allocate_terms(colptr, terms)
    for term in terms
        colptr[term.scalar_term.variable_index.value + 1] += 1
    end
end
function allocate_constraints0(colptr, model, ::Type{F}, ::Type{S}) where {F, S}
    cis = MOI.get(model, MOI.ListOfConstraintIndices{F, S}())
    funcs = MOI.get(model, MOI.ConstraintFunction(), cis)
    for i in eachindex(funcs)
        funcs[i] = MOI.Utilities.canonical(funcs[i])
        allocate_terms(colptr, funcs[i].terms)
    end
    return funcs
end
function allocate_constraints1(colptr, model, ::Type{F}, ::Type{S}) where {F, S}
    cis = MOI.get(model, MOI.ListOfConstraintIndices{F, S}())
    funcs = MOI.get(model, MOI.ConstraintFunction(), cis)
    for func in funcs
        MOI.Utilities.canonicalize!(func)
        allocate_terms(colptr, func.terms)
    end
    return funcs
end
function load_terms(colptr, rowval, nzval, terms, offset)
    for term in terms
        ptr = colptr[term.scalar_term.variable_index.value] += 1
        rowval[ptr] = offset + term.output_index - 1
        nzval[ptr] = term.scalar_term.coefficient
    end
end
function load_constraints(colptr, rowval, nzval, funcs, offset)
    for func in funcs
        load_terms(colptr, rowval, nzval, func.terms, offset)
        offset += MOI.output_dimension(func)
    end
    return offset
end
function load_scs(model::MOI.ModelLike, alloc_cons)
    colptr = zeros(Int, MOI.get(model, MOI.NumberOfVariables()) + 1)
    zero_cons = alloc_cons(colptr, model, MOI.VectorAffineFunction{Float64}, MOI.Zeros)
    nneg_cons = alloc_cons(colptr, model, MOI.VectorAffineFunction{Float64}, MOI.Nonnegatives)
    for i in 3:length(colptr)
        colptr[i] += colptr[i - 1]
    end
    rowval = Vector{Float64}(undef, colptr[end])
    nzval = Vector{Float64}(undef, colptr[end])
    offset = load_constraints(colptr, rowval, nzval, zero_cons, 0)
    load_constraints(colptr, rowval, nzval, nneg_cons, offset)
    for i in 2:length(colptr)
        colptr[i] = colptr[i - 1]
    end
    colptr[1] = 0
    return
end
```
I get the following:
```julia
julia> @time load_scs(model.model.model_cache.model, allocate_constraints1)

1.213951 seconds (220 allocations: 259.592 MiB)

julia> @time load_scs(model.model.model_cache.model, allocate_constraints0)

2.059930 seconds (12.01 M allocations: 1.223 GiB, 18.45% gc time)
```
I'm cheating though as I am assuming that the input variables indices are `1:n`.
Also, to implement `MOI.copy_to` we should return an `IndexMap`.
In fact, profiling the current `copy_to`, most of the time is spent mapping indices.
For every function, the function is copied once with `MOIU.canonical` and a second time with `map_indices`!
The copy with `map_indices` would be spared by just mapping the indices in `load_terms` but there is currently now way to spare the copy due to `MOIU.canonical`. This is the difference with `allocate_constraints1` and `allocate_constraints0`. This shows that allowing to modify the function of the `MOIU.Model` decrease the time by 2, the memory by 5 and the number of allocations by 500_000 !
Here are a few suggestions that would help make copying to SCS (and may other solvers I assume) from an `MOIU.Model` super-fast:
* Instead of having to always return an `MOIU.IndexMap` where the `varmap` is a `Dict`, we should allow to return something else in case the mapping is trivial, otherwise, hashing the keys would take all the time here
* Allow a model to show that the variables indices are simply 1:n. Maybe by returning `MOI.ContiguousIndices(n)` from `MOI.ListOfVariableIndices`.
* Allow a model to say that all constraint indices values span 1 to n.
* Allow a model to say that it allows another model to canonicalize in-place the functions that it returns.

If these 3 points are allows in MOI then it would allow `copy_to` to have the performance of `load_scs(model.model.model_cache.model, allocate_constraints1)` when copying a `MOIU.Model` to SCS.
The copy from another kind of model would maybe be a bit slower but it will still work.
The indexing return would be something like `IndexMap(::Nothing, ::Vector{MOI.ConstraintIndex})`. The `::Nothing` means that the mapping between variable indices is the identity. `Vector{MOI.ConstraintIndex}` is due to the fact that the constraint indices values of `MOIU.Model` are continguous. If the `MOIU.Model` being copied from has deleted variables or constraints then it would fallback to a more classical index mapping for variables or indices of course.
In fact, it would make sense to have an attribute `IndexMap <: MOI.AbstractModelAttribute` that would return the most appropriate type of index map for a given model.

**Comment by joaquimg** [comment]
A non breaking possibility would be to add a ContiguousIndex atrribute that would return true in case the indexes are contiguous.
In this case we follow the more efficient route.

**Comment by joaquimg** [comment]
Allowing in-place cannonicalize could also be an atrribute.

**Comment by blegat** [comment]
For the contiguous, we can start by just checking whether the output of ListOfVariableIndices and add_variables are contiguous indices, we'll see later if the performance gained by adding an attribute is worth it

**Comment by blegat** [comment]
I tested with the `I, J, K` + `sparse` option. The advantage is that we don't need to canonicalize but the disadvantage is that we have 3 vectors of the length of `nterms` (`I`, `J` and `K`) and we have to call `sparse` at the end.
```julia
function load_terms(I, J, K, terms, offset)
    for term in terms
        push!(I, offset + term.output_index)
        push!(J, term.scalar_term.variable_index.value)
        push!(K, term.scalar_term.coefficient)
    end
end
function load_constraints(I, J, K, model, F, S, offset)
    cis = MOI.get(model, MOI.ListOfConstraintIndices{F, S}())
    funcs = MOI.get(model, MOI.ConstraintFunction(), cis)
    for func in funcs
        load_terms(I, J, K, func.terms, offset)
        offset += MOI.output_dimension(func)
    end
    return offset
end
function load_scs(model::MOI.ModelLike)
    I = Int[]
    J = Int[]
    K = Float64[]
    offset = load_constraints(I, J, K, model, MOI.VectorAffineFunction{Float64}, MOI.Zeros, 0)
    load_constraints(I, J, K, model, MOI.VectorAffineFunction{Float64}, MOI.Zeros, offset)
    return I, J, K
end
using SparseArrays
function total_load(model::MOI.ModelLike)
    @time I, J, K = load_scs(model)
    @time sparse(I, J, K)
    return
end
```
We can see below that even the first part is slower than the previous approach.
We would improve it by using `resize!` for each function instead of `push!`ing each term but as `sparse` is 0.3 seconds, it cannot beat the previous approach:
```julia
0.196528 seconds (10.75 k allocations: 99.362 MiB, 32.40% gc time)
0.300498 seconds (19 allocations: 152.695 MiB)
```
