### ISSUE TITLE
Support newest version SCS v2.1.2

### ISSUE THREAD

**Issue by migarstka** [jump-dev/SCS.jl#188]
It would be great if you could update the wrapper to download the binaries for the latest tagged version v2.1.2.

**Comment by kalmarek** [comment]
https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/tag/SCS-v2.1.2%2B0
it's out there ;)

**Comment by blegat** [comment]
We should update the `download_info` of `deps/build.jl`

**Comment by kalmarek** [comment]
@blegat I forgot, thanks;
https://github.com/JuliaOpt/SCSBuilder/pull/2
the situation with BB across julia version is kind of a mess.
Btw. why SCSBuilder is in JuliaOpt and not jump-dev?

**Comment by blegat** [comment]
It's not using the SCSBuilder's binaries anymore but the ones from yggdrasil
