### ISSUE TITLE
Segmentation Fault on trivial example

### ISSUE THREAD

**Issue by votroto** [jump-dev/SCS.jl#193]
# Problem
Segmentation fault
# Versions
SCS v2.1.2
SCS.jl package version 0.6.6
Julia version 1.4.2

# MWE
```
using JuMP
using SCS

m = Model(SCS.Optimizer)

@variable  m x
@variable  m y
@constraint(m, x >= 0)
optimize!(m)
```

**Comment by kalmarek** [comment]
no longer segfaults on `master` of SCS. @votroto could you confirm?

probably this was due to invalid sparse matrix initialization, fixed by #191

**Comment by votroto** [comment]
Yep, you were right, sorry.

On a (vaguely) related note, what's going on with the requirement on building `scslib` manually?

**Comment by kalmarek** [comment]
no need to be sorry ;)

short story: building manually is purely optional. 

longer story: If you know know how to squeeze more perf out of scs libraries by building for local machine (e.g. with `march=native`) or with `openmp` support (which affects only the projection step of the solver) then please try and let me know ;)
Additionally, on master, you can access to the indirect solver on gpu (if it's CUDA enabled) if you build one as in the README.

**Comment by votroto** [comment]
Actually, in that regard I might need your help instead. 
I am unsure if there is a permission problem in build.jl or a with the ArchLinux distribution of Julia. I have no insight into Julia package build processes.

When I try to `add SCS` (irrespective if its the PKG version or Master from git) I get the following:

```
(@v1.4) pkg> add https://github.com/jump-dev/SCS.jl.git
   Updating git-repo `https://github.com/jump-dev/SCS.jl.git`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [c946c3f1] + SCS v0.7.0 #master (https://github.com/jump-dev/SCS.jl.git)
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [4536629a] + OpenBLAS_jll v0.3.9+5
  [c946c3f1] + SCS v0.7.0 #master (https://github.com/jump-dev/SCS.jl.git)
  [f4f2fc5b] + SCS_jll v2.1.2+0

(@v1.4) pkg> build SCS
   Building SCS → `~/.julia/packages/SCS/cvzBo/deps/build.log`
┌ Error: Error building `SCS`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libscsindir"], :indirect, "Prefix(/home/votroto/.julia/packages/SCS/cvzBo/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at /home/votroto/.julia/packages/BinaryProvider/U2dKK/src/Products.jl:419
│  [2] top-level scope at /home/votroto/.julia/packages/SCS/cvzBo/deps/build.jl:82
│  [3] top-level scope at none:5
│ in expression starting at /home/votroto/.julia/packages/SCS/cvzBo/deps/build.jl:82
└ @ Pkg.Operations /build/julia/src/julia-1.4.2/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:899

```

Curiously the package `CSDP` is in a very similar situation, but does not cause an error on my machine.
Is it an SCS problem or a distribution problem?

**Comment by votroto** [comment]
Wait a minute. What is the problem with building locally? You already recommend building with OpenMP support in your README. 

My manual build is trivially:
```
git clone https://github.com/cvxgrp/scs.git
cd scs
make CFLAGS="-Ofast -march=native" DLONG=1 USE_LAPACK=1 USE_OPENMP=1 out/libscsdir.so out/libscsindir.so
```
No problems so far.

**Comment by kalmarek** [comment]
there's no problem building locally, just make sure you link against the same openblas library as julia is using;

In the in julia-1.3 times (pre OpenBlas_jll) I used this script:
https://gist.github.com/kalmarek/1ddc06f2d76f6b6c343bf7cb9be98d75

the problem in build.jl is probably due to the wrong (i.e. systems) OpenBLAS linked during build resulting in missing symbols (underscore suffix). Can you show `ldd libscsindir.so`?

**Comment by votroto** [comment]
Sure, this is the working one. Everything is, of course, linked to systems libraries (i.e. linked with `-lopenblas`):
```
$ ldd libscsindir.so 
linux-vdso.so.1 (0x00007ffe219fd000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f6c007e3000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f6c007d8000)
libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f6c00797000)
libopenblas.so.3 => /usr/lib/libopenblas.so.3 (0x00007f6bff5d1000)
liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f6bfef0e000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6bfeeec000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f6bfed23000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f6c00979000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f6bfed1d000)
libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x00007f6bfea56000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f6bfea3c000)
libquadmath.so.0 => /usr/lib/../lib/libquadmath.so.0 (0x00007f6bfe9f1000)
```

**Comment by kalmarek** [comment]
ok, what exactly is not working?
is your julia using systems openblas?

btw. if julia uses different openblas than your scslibs then you risk inconsistent ABIs and undefined behaviours (if both libs export a symbol which one is called? and so on).

**Comment by votroto** [comment]
My only issue seems to be identical to https://github.com/jump-dev/SCS.jl/issues/194#issue-673098930

i.e. the build by Julia of the Julia interface `SCS.jl` fails unless `scslib.so` is built manually first, and it has something to do with generating `deps.jl` by `build.jl`.

Forget I said anything else. I don't even understand why the interaction between two completely separate programs is preconditioned on them using the same library for math internally. I could see the problem if one was built on different stdlibs. But surely BLAS internals do not leak all the way to the ABI of scs, do they?.

**Comment by kalmarek** [comment]
julia 1.3+ doesn't use `build.jl`/`deps.jl`:
https://github.com/jump-dev/SCS.jl/blob/6611207d8759cb4a7a1f8c10bcff606f0ccb471a/src/SCS.jl#L3

It seems that you're using 1.4 (from logs above), but probably forgot to unset `JULIA_SCS_LIBRARY_PATH`, so `SCS.jl` is trying to use the manually installed version? I can only guess here ;)

If you `dlopen` two libraries which export the same symbols but have incompatible ABI (like systems openblas and the one from `OpenBLAS_jll`, for example), you risk that functions will be called non-deterministically (from either library) and this may (will) result in segfaults due to ABI incompatibility.

https://stackoverflow.com/questions/42330182/program-use-two-conflicting-shared-libraries

**Comment by votroto** [comment]
I can't believe I never knew that, thanks for the link. Everything is solved then. Thanks!
