### ISSUE TITLE
Help with SCS documentation

### ISSUE THREAD

**Issue by bodono** [jump-dev/SCS.jl#223]
Thanks for all the hard work you have done on updating this API for the SCS 3.0 release.

If anyone has any spare cycles I would appreciate some help on the Julia documentation for the website, currently hosted [here](https://www.cvxgrp.org/scs/). In particular the Julia install instructions, Julia API, and an example or two in Julia.

Also please add the names and/or handles of the main maintainers of SCS.jl to the website. Even if nobody has time to help with the website this should be done to give credit where it is due. In general if you see anywhere in the website that needs improvement I am happy to take PRs or issues, especially where it concerns giving credit to other contributors!

**Comment by odow** [comment]
I'll take a look

**Comment by odow** [comment]
PRs:

 - https://github.com/cvxgrp/scs/pull/172
 - https://github.com/cvxgrp/scs/pull/173
 - https://github.com/cvxgrp/scs/pull/174

**Comment by odow** [comment]
Fixed upstream. If anyone is reading this in the future and has suggestions for doc improvements, I'm sure @bodono would take more PRs.

**Comment by bodono** [comment]
Thanks again for your help, and yes, PRs very welcome!
