### ISSUE TITLE
Documentation of scs_solve

### ISSUE THREAD

**Issue by VHarisop** [jump-dev/SCS.jl#239]
There are some minor inconsistencies in the low-level wrapper's documentation.

1. While the wrapper supports specifying a matrix `P`, the function signature in the [README](https://github.com/jump-dev/SCS.jl/blob/master/README.md?plain=1#L140) does not match the implementation.

2. The README states that `P` [must be a positive semidefinite symmetric matrix](https://github.com/jump-dev/SCS.jl/blob/master/README.md?plain=1#L162), but the SCS documentation specifies that [only the upper triangular part of `P` should be passed](https://www.cvxgrp.org/scs/api/c.html?highlight=upper%20triangular).
On that note, It seems that `scs_solve` does not extract the upper triangular part of `P`:
```julia
using SCS      # using the `master` branch
using LinearAlgebra

P = [2 1; 1 2]

# QP: min x'Px  s.t. x >= 0 - optimal solution: 0

# The call below will warn that P is not upper triangular. Changing P to triu(P) will work as expected.
scs_solve(
  SCS.DirectSolver,
  2,
  2,
  [-1 0; 0 -1.0],
  P,
  zeros(2),
  zeros(2),
  0,
  2,
  zeros(0),
  zeros(0),
  zeros(Int, 0),
  zeros(Int, 0),
  0,
  0,
  zeros(0),
)
```

**Comment by odow** [comment]
Note that the current `master` is for SCS 3.0 and is not officially released. We're still working out some issues, particularly with the GPU.

The latest release for SCS.jl is v0.8.1, https://github.com/jump-dev/SCS.jl/tree/v0.8.1, and does not support SCS 3.0.

**Comment by odow** [comment]
Okay, thanks for pointing these out. I've updated the docstring and README here: https://github.com/jump-dev/SCS.jl/pull/240
