### ISSUE TITLE
GPU build failing

### ISSUE THREAD

**Issue by odow** [jump-dev/SCS.jl#245]
Our GPU build has never worked with SCS 3.0. We merged in order to not have a giant PR: https://github.com/jump-dev/SCS.jl/pull/221#issuecomment-1006159547

We should find and fix the issue.

**Comment by odow** [comment]
@kalmarek what is your thought on tagging a new release even though the build is failing?

**Comment by kalmarek** [comment]
@odow I'm happy releasing 0.9 even though GPU doesn't work;

unfortunately gpuindirect solver doesn't work properly on the only machine with CUDA I have access to (see https://github.com/cvxgrp/scs/issues/180) hence slow progress on the issue.

**Comment by odow** [comment]
Hmm yeah it's suspicious that the BuildKite is segfaulting at about the same place that your CUDA run is complaining. This is probably an upstream issue, rather than something in SCS.jl or the JLL.

I'll tag a new release.

**Comment by NikEyX** [comment]
Has there any progress on this? GPU support doesn't currently seem to work.

**Comment by odow** [comment]
No progress. I don't have a GPU. It may require some upstream fixes to SCS.

**Comment by kalmarek** [comment]
@NikEyX I don't have a running access to CUDA gpu, so it's very hard for me to work on this;
the GPU solver is not recommended by the upstream as far as I can remember, so not much incentive here as well.

If you're willing to spend time on pardiso/mkl then you can also lend me your hand in getting #255 over the finish line ;) though just not building `scs-mkl` on x86 would be the quickest solution ;P

Currently I'd suggest to use the `DirectSolver` and experiment with `acceleration_lookback` and `alpha` (gridsearch wouldn't hurt).
Note that `acceleration_lookback` can also take negative values for type two acceleration ;)
