### ISSUE TITLE
SCS now has better support for caching and reusing the workspace

### ISSUE THREAD

**Issue by bodono** [jump-dev/SCS.jl#246]
The C level interface now has an [`scs_update` function](https://www.cvxgrp.org/scs/api/c.html#c-interface).

This allows the user to reuse the workspace for multiple choices of `b` and `c` vectors (eg reusing the matrix factorization). Also works well with warm-starting (see the `scs_solve` function). It would be great for SCS.jl to make use of this functionality.

As an example you can see the python interface [here](https://www.cvxgrp.org/scs/api/python.html#python-interface).

Concrete usage example (in python) [here](https://www.cvxgrp.org/scs/examples/python/lasso.html#py-lasso). See the use of `solver.update` and `solver.solve` functions in the code snippet.

**Comment by kalmarek** [comment]
@bodono Thanks for letting us know! I still need to find some time to bring SCS_jll to 3.1, but then 3.2 is already around the corner ;)

**Comment by odow** [comment]
Hmm. It's actually non-trivial to update this. We spent a lot of time recently improving the architecture in JuMP for "one-shot" solvers that don't support modification and SCS was the prime example!

**Comment by bodono** [comment]
No problem at all, I have no expectations of an ETA! The single shot solve function is still available so will be backwards compatible.

**Comment by kalmarek** [comment]
implemented in #251
