### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by chelseas** [jump-dev/SCS.jl#254]
I need to build PyCall, which precompiles a package my lab develops: NeuralVerification.jl which needs to build SCS. But when I try to build SCS I get this error:

```
(verification) pkg> build SCS
    Building SCS → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/936d43feaceae3290472ddf800b496be094d727b/build.log`
ERROR: Error building `SCS`:
ERROR: LoadError: LibraryProduct(nothing, ["libscsindir"], :indirect, "Prefix(/home/csidrane/.julia/packages/SCS/28Svy/deps/usr)") is not satisfied, cannot generate deps.jl!                                                                                                               sfied, cannot generate deps.jl!
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] write_deps_file(depsjl_path::String, products::Vector{LibraryProduct}; verbose::Bool, isolate::Bool)
   @ BinaryProvider ~/.julia/packages/BinaryProvider/U2dKK/src/Products.jl:419
 [3] top-level scope
   @ ~/.julia/packages/SCS/28Svy/deps/build.jl:94
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [5] top-level scope
   @ none:5
in expression starting at /home/csidrane/.julia/packages/SCS/28Svy/deps/build.jl:94
```
Any help?

**Comment by odow** [comment]
It looks like you've added an old version of SCS.jl. Make sure to install `SCS.jl` version 1.0.0 or later.

**Comment by chelseas** [comment]
Well I'm trying to use MathOptInterface and that seems to have an explicit restriction to 0.5.1-0.7.1

**Comment by odow** [comment]
The underlying issue is https://github.com/sisl/NeuralVerification.jl/issues/201. 

But the SCS build should have worked, even if you are on an old version.  What is `versioninfo()`?

**Comment by chelseas** [comment]
Also it mysteriously stopped erroring for no reason at all? SCS still at 0.7

**Comment by odow** [comment]
> Also it mysteriously stopped erroring for no reason at all?

What do you mean?

**Comment by chelseas** [comment]
Sorry losing track of this convo across the three issues in three different repos haha.
This is versioninfo():
```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
  ```

**Comment by odow** [comment]
> Sorry losing track of this convo across the three issues in three different repos haha.

Haha. So there are two issues:
 1. NeuralVerification should remove the dependency on GLPKMathProgInterface and allow you to install the latest versions of each package
 2. Old versions SCS would ideally still install

2 is the fault of SCS.jl, but I don't have a strong incentive to debug this, when the solution is to fix 1.

**Comment by chelseas** [comment]
ok, great thank you I will look into this!

**Comment by odow** [comment]
Closing because this is best fixed by changes to NeuralVerification: https://github.com/sisl/NeuralVerification.jl/issues/201
