### ISSUE TITLE
WARNING: could not import SCS_MKL_jll.MKL_jll into SCS

### ISSUE THREAD

**Issue by kalmarek** [jump-dev/SCS.jl#278]
https://github.com/kalmarek/2306.12358/actions/runs/5395718537/jobs/9798492538#step:7:5
https://github.com/kalmarek/2306.12358/actions/runs/5395718537/jobs/9798492538#step:8:5
and in all other jobs;

Also happens locally.

I guess this is due to our shenanigans with SCS_MKL_jll?

**Comment by WellWellww** [comment]
Will this affect the performance of `SCS.MKLDirectSolver`?

**Comment by kalmarek** [comment]
no

**Comment by odow** [comment]
Closing in favor of #274. I have a plan for a more complete fix.
